### ISSUE TITLE
What the actual fuck!? 😳

### ISSUE THREAD

**Issue by Annihil** [Ffloriel/alina#1]
Hi double zero scraipt,

I hope this issue finds you well,

Soooo, care to explain what is this repo all about?

@contrarian is also kinda confused

Which Alina are you referring to, and why?
Can you push her on npm?
Is it possible to change her license?

I'm watching you,

BaP, the one and only.

**Comment by Ffloriel** [comment]
Hi @Annihil **GODZ** ,

> Soooo, care to explain what is this repo all about?

I can explain to you what alina is about. alina is a set of components that will constitute a UI Framework. This UI will be based mostly on Invision design kits. Once done, I should have all the most used components necessary to build an application at end. This will allow me to create application with a proper design at record speed. In the future. Creating application with alina should be fairly easy.

> Which Alina are you referring to, and why?

I don't understand the question. This is just the name I choose for the repository. Since it's related to design, I felt it could be a good name.

> Can you push her on npm?

I am not planning to publish alina yet. It will stay private until I feel like it's good enough.

> Is it possible to change her license?

You can change alina license. I'm not really familiar with the licenses so I choose MIT License. Do you have any suggestions about this particular subject?

I'll keep an eye on you as well,

Flo, the best in the world.

**Comment by contrarian** [comment]
I'm still kinda confused.

Huh?,
    Biggest G
